version: '3.7'

services:
  server:
    image: ionrev/server:latest
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    env_file:
      - server/docker/server.env

  client:
    image: ionrev/client:latest
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - server
    env_file:
      - client/docker/client.env
